In [2]:
import tensorflow as tf
import numpy as np

In [3]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
x = tf.constant(x)
x

<tf.Tensor: id=0, shape=(10,), dtype=int32, numpy=array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])>

In [6]:
x = tf.square(x)
x

<tf.Tensor: id=1, shape=(10,), dtype=int32, numpy=array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])>

In [10]:
x = tf.reshape(x, (2, 5))
x

<tf.Tensor: id=8, shape=(2, 5), dtype=int32, numpy=
array([[ 0,  1,  4,  9, 16],
       [25, 36, 49, 64, 81]])>

In [11]:
x = tf.cast(x, tf.float32)
x

<tf.Tensor: id=9, shape=(2, 5), dtype=float32, numpy=
array([[ 0.,  1.,  4.,  9., 16.],
       [25., 36., 49., 64., 81.]], dtype=float32)>

In [15]:
y = tf.constant(4, dtype=tf.float32)
y

<tf.Tensor: id=12, shape=(), dtype=float32, numpy=4.0>

In [16]:
result = tf.add(x, y)
result

<tf.Tensor: id=13, shape=(2, 5), dtype=float32, numpy=
array([[ 4.,  5.,  8., 13., 20.],
       [29., 40., 53., 68., 85.]], dtype=float32)>